### PR TITLE
Docker Compose (or Fig) support

### PR DESCRIPTION
**Pull request by kingcody**
Interested?

### CODE REVIEW

**Comment by ayufan** [comment]
It's nice, but do we really need it?

I think that it's better to prepare simple bash script which will install or upgrade multi-runner. You just have to paste it on docker enabled server. Something like that:
```bash
bash -c $(curl https://raw...github.com/.../multi-runner/install.sh)
```

It would prepare data volume, pull the image, and remove (if needed) and run multi-runner.

**Comment by ayufan** [comment]
This requires you to install Docker and Docker Compose. In that script we could simply include docker dependency.

**Comment by kingcody** [comment]
It would be for people who already use Fig or Docker Compose. However, if you think it would be bloat or confusing to other users, then maybe just the `docker-compose.yml` for example and quick setup for those already familiar with the two.

**Comment by ayufan** [comment]
I still think that we have too many possible installation methods already :) Generally I like the idea with simple `curlable` installation script that will do all magic and what it does beneath it's not really important :) There is such installation for system packages (deb and rpm). We now have pretty simple Docker installation and with having Docker Compose I think that it would be too much.

**Comment by kingcody** [comment]
I see, no worries (:

**Pull request closed without merging**
