### PR TITLE
Update setup docs for OS X and Linux

### PR DESCRIPTION
**Pull request by maxlazio**

### CODE REVIEW

**Comment by ayufan** [comment]
It works as an service on OSX.


On Monday, April 20, 2015, Marin Jankovski <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ayufan/gitlab-ci-multi-runner/pull/28
> Commit Summary
>
>    - Update setup docs for OS X.
>    - Update linux installation documentation.
>
> File Changes
>
>    - *M* docs/install-on-linux.md
>    <https://github.com/ayufan/gitlab-ci-multi-runner/pull/28/files#diff-0>
>    (26)
>    - *M* docs/install-on-osx.md
>    <https://github.com/ayufan/gitlab-ci-multi-runner/pull/28/files#diff-1>
>    (54)
>
> Patch Links:
>
>    - https://github.com/ayufan/gitlab-ci-multi-runner/pull/28.patch
>    - https://github.com/ayufan/gitlab-ci-multi-runner/pull/28.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayufan/gitlab-ci-multi-runner/pull/28>.
>


-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by maxlazio** [comment]
@ayufan I didn't have any luck with it as a service. Was there anythng special I had to do to make it work?

**Comment by ayufan** [comment]
I just did:
```gitlab-ci-multi-runner install / run```

That's all. There's one thing to be noted. The service on OSX is installed as UserService, so it only works in context of user. If you want to have it run on machine startup you have to enable auto login for that user.

**Comment by ayufan** [comment]
@maxlazio Had you time to check it?

**Comment by maxlazio** [comment]
@ayufan I think I am misunderstanding something then. I thought that service means that you start it up once and forget about it. With `gitlab-ci-multi-runner run` you have to have the terminal window  open as it is ran in foreground. 

Also, running `gitlab-ci-multi-runner install` gives `Failed to install GitLab-CI Multi-purpose Runner: user: Current not implemented on darwin/amd64` error. That is why I suggested changes in this PR.

**Comment by ayufan** [comment]
This is cross compilation bug which I fixed. Please try the 0.1.17 or grab this: ```wget http://repo.ayufan.eu/gitlab-ci-multi-runner/master/binaries/gitlab-ci-multi-runner-darwin-amd64``` (it's beta release built from master branch)

**Comment by ayufan** [comment]
Either way I'll give it try and create osxpkg.

**Comment by huglester** [comment]
@ayufan @maxlazio sorry for flooding your pull request. 

Have you disabled the issues? I was now trying to install fresh docker containers on OpenVZ and have some howtos prepared. But now I have some issues running it on centos.. and wanted to ask somewhere:)

**Comment by ayufan** [comment]
I think that you found the way :)

It was moved to GitLab.com issue tracker.

**Pull request closed without merging**
