### PR TITLE
Allow shell executor to inherit environment vars

### PR DESCRIPTION
**Pull request by jeffreykoetsier**
This fixes issue 'PATH issue with Shell executor #1'

In the config.toml you are able to specify a bool to inherit all the environment vars of the running process. Defaults to false to conform to current behaviour.

### CODE REVIEW

**Comment by ayufan** [comment]
Thanks. I think that more common approach is that you think that env are inherited. Maybe we could expose option to disable it and enable it by default?

**Comment by jeffreykoetsier** [comment]
I set default to false so it won't change the existing behaviour. I was really surprised it didn't inherit the environment vars by default. So it seems already three people are assuming it would inherit by default.

Changing the default behaviour to 'default inherit' with an opt-out config option would be my preference.

Let me know if you want me to update the pull request.

**Comment by ayufan** [comment]
Yes. It's expected behaviour. If you can I would be happy to merge it :)

**Comment by ayufan** [comment]
Thanks. With a few other changes I released it as 0.1.8.

**Pull request merged**
